name: nf_kicks
description: Social distanced shopping

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_plugin_android_lifecycle: ^1.0.2
  flutter_dotenv: ^3.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_storage: ^5.2.0
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  google_sign_in: ^4.5.6
  flutter_login_facebook: ^0.4.0+1
  provider: ^4.3.2+2
  google_fonts: ^1.1.1
  password_compromised: ^1.0.0
  form_field_validator: ^1.0.1
  google_maps_flutter: ^1.2.0
  geolocator: ^6.2.0
  flutter_snake_navigationbar: ^0.4.1+3
  cloud_firestore: ^0.14.3+1
  intl: ^0.16.1
  qr_flutter: ^3.2.0
  toast: ^0.1.5
  image_picker: ^0.6.7+17
  image_cropper: ^1.3.1
  encrypt: ^4.1.0
  flutter_credit_card: ^0.1.3
  stripe_payment: ^1.0.11
  http: ^0.12.2
  flutter_nfc_reader: ^0.1.0
  trust_fall: ^1.0.4
  connectivity: ^2.0.2
  crypto: ^2.1.5
  simple_logger: ^1.7.0

dev_dependencies:
  mockito: ^4.1.3
  flutter_config: ^1.0.8
  import_sorter: ^4.4.1
#  lint: ^1.3.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #   - family: PermanentMarker
  #     fonts:
  #       - asset: fonts/PermanentMarker-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
